### ISSUE TITLE
Why is the origin in the lower left and why is it constrained to 256x256?

### ISSUE THREAD

**Issue by jmiller-boundless** [ElectronicChartCentre/java-vector-tile#1]
I am trying to create a test implementation to serve vector tiles but am confused by the following:
* Add a feature with layer name (typically feature type name), some
     * attributes and a Geometry. The Geometry must be in "pixel" space 0,0
     * lower left and 256,256 upper right.
Is the lower left origin part of the Vector Tile standard?  Typically Canvas and screen coordinate systems have an upper left origin?  Any recommendations for tools to go from Spherical Mercator coordinates (plus image size) to this lower left format?  Also, why 256x256?  Could these dimensions be made configurable?
Thanks

**Comment by halset** [comment]
The origin and 256x256 is from the spec.

You will typically use X, Y and Z from the Tile URL and pick your geometries/attributes from your data store. You will then reproject the geometries to the coordinate system of the tile. Then, the geometries are ready to use with the VectorTileEncoder.

**Comment by halset** [comment]
Closing this..
