### ISSUE TITLE
Clipping at the tile boundary for Point types - clarification sought.

### ISSUE THREAD

**Issue by timrobertson100** [ElectronicChartCentre/java-vector-tile#12]
I am not sure if this is a bug, a feature or quite possibly a misunderstanding on my part.

When dealing with point data it appears that the extent is ignored and point geometries are clipped at the tile boundary here:
https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/java/no/ecc/vectortile/VectorTileEncoder.java#L182

This seems undesirable in many circumstances since it is often the case that a point will end up on a rendering engine such as Mapnik, where the points are styled to be larger than a pixel.  Unless a buffer can be provided, the renderer cannot handle tile boundaries correctly when e.g. rendering a 10pixel circle per point feature.  The only option is then to pass 9 separate tiles to the renderer instead of 1 with a buffer.

Could you please confirm if my understanding is correct?  It is nicely documented that this can be overridden, although I'm not sure this desirable default behaviour.

Attached is an example of the effect when a buffer can't be passed.

![screenshot 2016-05-23 15 53 59](https://cloud.githubusercontent.com/assets/237221/15473105/a8fac422-20fe-11e6-93e9-7493b3dc062c.png)

**Comment by timrobertson100** [comment]
[It would also be nice to make a protected accessor to polygonClipGeometry to allow this to be used when overridding]

**Comment by timrobertson100** [comment]
Having explored this further, I think I do understand it correctly, but I'd suggest changing the behavior so clipping be at the extent regardless of the Geometry type.  The justification for this is that if the caller constructed the encoder with an extent, they are indicating that they do indeed need a buffer, otherwise they would construct it with 0.

**Comment by halset** [comment]
Thank you. Looks like this fixes a problem for me as well. Please try out v1.1.0.

**Comment by timrobertson100** [comment]
Thank you for the quick turnaround @halset
