### ISSUE TITLE
Decoder Filters only support a single layer

### ISSUE THREAD

**Issue by timrobertson100** [ElectronicChartCentre/java-vector-tile#15]
When decoding large tiles, the ability to pass in a filter is great.  However, Filter is package private so cannot be customised by implementations and decoder only allows a single layer to be provided.  

A useful addition would be the ability to filter by multiple layers.

**Comment by halset** [comment]
Thank you. Closing this now after me ring #16

**Comment by timrobertson100** [comment]
Thanks for the quick turnaround again.

If it is not too much trouble, could you please release 1.1.2?  It would save me setting up jenkins to push to our nexus repository just to build snapshot releases.

**Comment by halset** [comment]
Done

**Comment by timrobertson100** [comment]
Thanks @halset 
(I think you might want to bump pom to 1.1.3-SNAPSHOT)

**Comment by halset** [comment]
done
