### ISSUE TITLE
Update documentation for correct pixel directions

### ISSUE THREAD

**Issue by jeffreyeriksondg** [ElectronicChartCentre/java-vector-tile#17]
First, thanks for the great work on this library . . . it has saved me a great deal of time!

I've noticed that, in a few places in the documentation, it's mentioned that the encoder pixel space starts at (0,0) in the lower-left and goes to (256,256) in the upper-right, e.g. from the README on the front page: `// The Geometry uses (0,0) in lower left and (256,256) in upper right.`.  The Mapbox Vector Tile specification version 2.1 states: `The upper left corner of the tile (as displayed by default) is the origin of the coordinate system. The X axis is positive to the right, and the Y axis is positive downward.`

It appears that the implementation of the encoder class follows the spec correctly; however, the documentation has the Y-axis flipped.  It's possible I'm misunderstanding something, since I'm new at using the MVT format, but when I rendered the tile output in Leaflet, it was indeed flipped vertically when I followed the documentation to convert my features to a 256x256 grid with (0,0) in the lower-left and (256,256) in the upper-right.  Flipping the the tile so that (0,0) was in the upper-left and (256,256) was in the lower-right caused the tile to render correctly.

I'd suggest updating the documentation so that new users won't be confused as to how to map features to the tile grid space.

**Comment by halset** [comment]
Thanks. Updated in master and jts-vividsolutions, but not part of a release yet.
