### ISSUE TITLE
Encoder splits MULTIPOLYGONS

### ISSUE THREAD

**Issue by jincheng-factual** [ElectronicChartCentre/java-vector-tile#18]
Thanks for the great work! I'm trying to encode and serve some geo data in vector tile format and this library has been super useful.

I'm wondering why VectorTileEncoder splits multi-polygons into multiple polygons and encodes them separately, though. According to the Vector Tile 2.0 spec, it seems like multi-polygons should just be encoded as VectorTile's POLYGON type with no splitting. The Encoder class also deals with multi-points and multi-linestrings appropriately, so I'm not sure why multi-polygons are the special case.

**Comment by halset** [comment]
Please create a pull-request if you want this feature.

**Comment by halset** [comment]
Fixed in 1.2.4 and 1.3.4.
