### ISSUE TITLE
Update to vector tile spec v2

### ISSUE THREAD

**Issue by timrobertson100** [ElectronicChartCentre/java-vector-tile#19]
Using this with the latest MapboxGL JS libraries (0.28) will give warnings that the tiles are not using v2 tile spec:
   `Vector tile source "gbif" layer "regression" does not use vector tile spec v2 and therefore may have some rendering errors.`

Would you welcome a pull request to address this?

**Comment by timrobertson100** [comment]
I plan to work on this tomorrow.  
If it is not massively invasive, would someone be willing to review and release it please?

**Comment by timrobertson100** [comment]
This is strange.  I am using v1.1.2 but the latest mapbox GL clients give the warning despite the code setting version 2 thanks to this commit:

https://github.com/ElectronicChartCentre/java-vector-tile/commit/30de1f02d27c8175e63945b342118bedad880cf5

Closing this issue as reported in error, and will open a new one if it is a server side issue.  At this point, I suspect not.

**Comment by halset** [comment]
Thank you for the report. I do not get the warning with Mapbox GL clients. Both JS 0.28.0 and the latest GL Native.

**Comment by timrobertson100** [comment]
Confirmed that this was just an error on my part.
