### ISSUE TITLE
Memory crash

### ISSUE THREAD

**Issue by maiden71** [ElectronicChartCentre/java-vector-tile#2]
Hi ! 
    
I'm trying to have (on android) online map using sources from mapbox and offline maps using mbTiles. So i needed a decoder to get the data. The one I'm using is too slow (about few seconds to load the screen) so I tried with yours. Performance problems have gone away but now I have crash due to lack of memory after some seconds (it depends of the quantity of data on the screen). 

Have you ever had this problem ? 

I thought it's from the auto-generated VectorTile.java (which contains 4272 lines), so I've tried to generate a new one with the google.protobuf.nano lib (now it contains 781 lines) but now I have to modify every called methods in the decoder because they don't exists anymore or their name have changed. 

Have you got an idea to improve the consumption of memory of you code. And can you tell us what kind of options have you used to generate the VectorTile.

Thank you ! 
Regards 

Pierre

**Comment by halset** [comment]
Thanks for the feedback! I have not used java-vector-tile on Android, only on server. Improved memory handling would be nice. Perhaps by changing VectorTileDecoder to be stream based ínstead of decoding all features and geometries before returning.

**Comment by halset** [comment]
Thanks for the tip on protobuf.nano as well!

**Comment by halset** [comment]
The first attempt will return an Iterable<Feature> from the decode method. That way, the attributes and geoemtries will be created as you get the Features, not all in one go. This reduces memory consumption some, but not as much as javanano.

I have taken a look at javanano and have ported most of the decoder/encoder over to javanano. However, I have some problems with the optional attribute fields.

**Comment by halset** [comment]
#3 is now updated with javanano. It does not work with numeric feature attributes with value 0 - those are handled as null :(

**Comment by maiden71** [comment]
Thank you for your responses ! You work fast ;) 

About the VectorTile generated with javanano, what options have you used ? I think the problem with the numeric values to 0 is from optionals fields (look here https://android.googlesource.com/platform/external/protobuf/+/master/java/README.txt). I tried to generate it with 
 "protoc --javanano_out=java_multiple_files=true,optional_field_style=accessors,store_unknown_fields=true:Test Test/vector_tile.proto" 
and now I have about 200 more code lines with new methods.

I was also wondering what "option optimize_for " you've used in proto ? 
I'm going to try your new TileDecoder improved with original VectorTile to save memory. 

Thank you again !

**Comment by halset** [comment]
Thanks for the tips on optional_field_style=accessors. It seem to solve the problem with the optional feature attributes with 0 value. I have updated #3 with this fix.

This is how I use protoc now. Added a section to README.md on it. Also in #3 

```
protoc --javanano_out=store_unknown_fields=true,optional_field_style=accessors:src/main/java/ src/main/resources/vector_tile.proto
```

**Comment by halset** [comment]
Have you been able to test this?

**Comment by maiden71** [comment]
Are you talking about your TileDecoder using FeatureIterator with Vector_Tile generated thanks to javanano ?

**Comment by halset** [comment]
Yes, I wonder if you have your app with pull-request #3. It is generated from javanano and works pretty well for me.

**Comment by maiden71** [comment]
Yes I've tried it.
It works good, I've no memory problems anymore (even on Android 5 devices ;) ), and it's runing faster than the previous version (about 2 times) of the app ! but i's still not enough ... So I'm working on the other process on the app, trying to improve it and get it fastest as possible. 

Thank you again ! ;)

**Comment by halset** [comment]
Okay. I have merget in #3 and close this for now. Thank you for the report and testing!
