### ISSUE TITLE
[Question] Mapbox GL js uses 512px tiles

### ISSUE THREAD

**Issue by rgtaylor1989** [ElectronicChartCentre/java-vector-tile#20]
Mapbox GL js uses 512px x 512px tiles 

https://www.mapbox.com/blog/512px-map-tile/

I noticed that java-vector-tile is creating 256px x 256px tiles .

Will this cause a problem with mapbox GL and is it possible to render 512px tiles? Does the tile pixel size even matter?

**Comment by halset** [comment]
The raster tiles are 512x512 from Mapbox, but the vector tile coordinate system can be controlled by the extent in the [VectorTileEncoder](https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/java/no/ecc/vectortile/VectorTileEncoder.java#L93). It works very well with both Mapbox GL JS and GL Native.
