### ISSUE TITLE
Topology problem

### ISSUE THREAD

**Issue by sunshine0576** [ElectronicChartCentre/java-vector-tile#21]
VectorTileEncoder
List<Integer> commands(Coordinate[] cs, boolean closePathAtEnd, boolean multiPoint)

       int _x = (int) Math.round(c.x * scale);
       int _y = (int) Math.round(c.y * scale);

“ Math.round ” Will undermine the geometry of the topology。
In most cases, this results in geometric destruction of the topology
Special circumstances, the line is greater than two, the ring is greater than three points, simplifying the data can not be decoded。

POLYGON((276 -9.971059, 275.694486 -11.216161,
 275.790837 -11.470391, 275.858638 -11.682043,
 274.721101 -12.110007, 274.274849 -12.936855,
 274.428308 -11.687796, 274.201221 -10.983723,
 274.746797 -9.867818, 274.394365 -9.660545,
 274.463186 -9.491113, 274.960824 -9.819437,
 274.565041 -10.965759, 274.645024 -11.502877,
 275.117082 -11.614186, 275.52707 -11.349726,
 275.928936 -9.91006, 276 -9.790078, 276 -9.971059))

**Comment by halset** [comment]
What should we use instead of `Math.round()`? We need it to be an int in some way. It seem to work pretty well for me.
