### ISSUE TITLE
Linestrings

### ISSUE THREAD

**Issue by karussell** [ElectronicChartCentre/java-vector-tile#22]
Thanks for this library!

Is it possible to use linestrings like so:

vtm.addFeature("isochrone", attributes, gf.createMultiLineString(lineStrings));

When I do this I get a result but when I use vtzero to show and check this file I get:

Error in layer 0 (feature 0): expected command 2 but got 1

**Comment by halset** [comment]
We use LineString a with this library to create tiles for Mapbox GL a lot.
