### ISSUE TITLE
Switch pbf library from nano to lite

### ISSUE THREAD

**Issue by aaime** [ElectronicChartCentre/java-vector-tile#26]
Nano is not supported, the Google suggestion is to switch to the "lite" version:
https://github.com/protocolbuffers/protobuf/issues/2730

It however seems lite will be released again only in Q3:
https://github.com/protocolbuffers/protobuf/issues/4769

**Comment by halset** [comment]
Okay. I switched from nano to protobuf-java. Is that fine with you, @aaime ?

**Comment by aaime** [comment]
Hi, I'm on the phone, internet access little clumsy... If lite is not released yet, the full version will do.

**Comment by halset** [comment]
Closing this now as lite does not seem to have been updated since 2016. The full version has worked for us for some time now. Just reopen if there is anything to do.
