### ISSUE TITLE
Wrong winding order for polygons vs Mapbox Vector tiles specification

### ISSUE THREAD

**Issue by aaime** [ElectronicChartCentre/java-vector-tile#28]
The specification says outer rings should be clockwise, and hole counter clockwise:
https://docs.mapbox.com/vector-tiles/specification/#winding-order

However the encoder code seems to be systematically generating the opposite order:

- for exterior rings, checks if not counter clock wise (aka clockwise), and if so, reverses it (making it CCW)
- for internal rings, check if they are CCW, and if so, reversed them (making them clockwise)

Am I missing anything here?

**Comment by long1eu** [comment]
Any news on this? Is this fixed?

**Comment by halset** [comment]
The library seem to produce polygon according to spec regardless of coordinate order. See https://github.com/ElectronicChartCentre/java-vector-tile/commit/cf6b828630c2918c97f1f71e7474be9b34a1ce78 . If not, please give more details.
