### ISSUE TITLE
Decoding Vector Tile file into a geoGSON file

### ISSUE THREAD

**Issue by alexhorban82** [ElectronicChartCentre/java-vector-tile#29]
Thanks for the great library!

According to the Vector tile specification (https://docs.mapbox.com/vector-tiles/specification/) original GeoJSON data is encoded into the proper tags of the vector tile protobuf.

![image](https://user-images.githubusercontent.com/33970317/63811891-ee255200-c8e5-11e9-9d88-94901268d96b.png)

Do we have methods to translate Vector Tile file into GeoJSON files ? It would great to be able to do that in the future

**Comment by halset** [comment]
Sorry, but out of scope for this library.
