### ISSUE TITLE
some map data have different show in different zoom level

### ISSUE THREAD

**Issue by ZChengL** [ElectronicChartCentre/java-vector-tile#30]
some map data have different show in different zoom level . for example I draw some walls, and the adjacent walls will fill the grey face between them;

![image](https://user-images.githubusercontent.com/19296715/67733506-843a3d80-fa39-11e9-9259-8d11ed987036.png)

![image](https://user-images.githubusercontent.com/19296715/67733519-8c927880-fa39-11e9-9264-7936db333383.png)

how to relsove this problem ? i need help

**Comment by chakravarthi-vl** [comment]
Hi Team
This issue is solved or not.

**Comment by halset** [comment]
Closing this as there are too little information. Please re-open if you have a reproduceable case.
