### ISSUE TITLE
Is it possible to deploy this jar to maven center repository

### ISSUE THREAD

**Issue by exotfboy** [ElectronicChartCentre/java-vector-tile#31]
Hi:

This is a wonderful tool for vector tile processing. However I found that the release jar have not been uploaded to maven center repository after 1.3.1, instead we have to use it from [ecc mvn repo](https://github.com/ElectronicChartCentre/ecc-mvn-repo).

However we can not access  ecc mvn repo directly, so the build job of the application will fail unless we  create our own proxy repo.

So ss it possible to deploy this jar to maven center repository as before?

**Comment by halset** [comment]
As stated in README, it is in the following repo:
```
<repository>
    <id>ECC</id>
    <url>https://maven.ecc.no/releases</url>
</repository>
```
