### ISSUE TITLE
Avoid reusing coordinate instance when closing rings

### ISSUE THREAD

**Issue by lcanet** [ElectronicChartCentre/java-vector-tile#36]
When reading polygons from MVT files, the rings are closed by pushing the first Coordinate instance to the end of the coordinates list. Since JTS Coordinate are mutable this may result in problems when using for instance JTS  [CoordinateFilter](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/CoordinateFilter.html)  because they modify the coordinates in place, resulting in the same object instance being modified twice.

A new Coordinate instance should be used for closing the rings.

Thank you

**Comment by halset** [comment]
@lcanet pull requests are welcome

**Comment by halset** [comment]
Thanks, @lcanet. Merged both. I will create releases.

**Comment by halset** [comment]
@lcanet, this is included in the latest releases.
