### ISSUE TITLE
EPSG 4326 JTS Vividsolutions Points to tile

### ISSUE THREAD

**Issue by nenadkitanovic89** [ElectronicChartCentre/java-vector-tile#37]
I have an issue displaying the points (JTS Vividsolutions, EPSG 4326) to tiles. The placement for all points on the map is wrong. 

` 
    private final GeometryFactory gf = new GeometryFactory(new PrecisionModel(), 4326);
...

VectorTileEncoder encoder = new VectorTileEncoder(256);

        points.forEach(point -> {
            final Point location = point.getLocation();
            Map<String, Object> userDataMap = new HashMap<>();
            userDataMap.put("icon", "red");

            double[] coords = latLonToPixels(location.getY(), location.getX());
            Point reprojectedPoint = gf.createPoint(new Coordinate(coords[0], coords[1]));
            log.info("Reprojected point: Lat={} Lon={} to x ={}, y ={}", location.getY(), location.getX(),
                    reprojectedPoint.getX(), reprojectedPoint.getY());
            encoder.addFeature("road", userDataMap, reprojectedPoint);
        });

// Finally, get the byte array
        byte[] encoded = encoder.encode();
        return encoded;

    private double[] latLonToPixels(double lat, double lon) {
        double sinLat = Math.sin(lat * Math.PI / 180.0);
        double pixelX = ((lon + 180) / 360) * 256;
        double pixelY = (0.5 - Math.log((1 + sinLat) / (1 - sinLat)) / (Math.PI * 4)) * 256;

        double[] result = new double[2];
        result[0] = pixelX;
        result[1] = pixelY;
        return result;
    }
`

**Comment by halset** [comment]
@nenadkitanovic89 , the library does not handle projecting the corrdinates. As stated in the README.md, the geometries should be transformed to 0-255x0-255 before sent to the encoder.
