### ISSUE TITLE
Some errors in spark

### ISSUE THREAD

**Issue by HarrietMa** [ElectronicChartCentre/java-vector-tile#40]
Hi, I followed the constructions and add the dependences in pom. But when I turn my project to jar and submit it to spark it showed some errors like this:

User class threw exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4, 9.117.197.230): java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
com/google/protobuf/GeneratedMessageV3$ExtendableMessage.getExtension(Lcom/google/protobuf/GeneratedMessage$GeneratedExtension;)Ljava/lang/Object; @2: invokevirtual
Reason:
Type 'com/google/protobuf/GeneratedMessage$GeneratedExtension' (current frame, stack[1]) is not assignable to 'com/google/protobuf/ExtensionLite'
Current Frame:
bci: @2
flags: { }
locals: { 'com/google/protobuf/GeneratedMessageV3$ExtendableMessage', 'com/google/protobuf/GeneratedMessage$GeneratedExtension' }
stack: { 'com/google/protobuf/GeneratedMessageV3$ExtendableMessage', 'com/google/protobuf/GeneratedMessage$GeneratedExtension' }
Bytecode:
0x0000000: 2a2b b600 23b0
at no.ecc.vectortile.VectorTileEncoder.encode(VectorTileEncoder.java:309)

So I wonder why it happens. Is it because the version of jdk? Mine is jdk1.8. 
Looking forward to your reply.
Harriet
<img width="1025" alt="企业微信截图_524e6dc6-ea34-4925-a249-9ead6956fe3f" src="https://user-images.githubusercontent.com/56391496/123372172-af31b780-d5b5-11eb-868b-d902f08b2e48.png">

**Comment by halset** [comment]
Could there be conflicting protobuf versions?

**Comment by HarrietMa** [comment]
I hava checked it. but I think other versions of protobuf have been omitted just like this:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElectronicChartCentre/java-vector-tile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ElectronicChartCentre/java-vector-tile] Some errors in spark (#40)





 
Could there be conflicting protobuf versions?

**Comment by halset** [comment]
Okay. I do not have any other suggestion. However, we should probably upgrade our protobuf version to something newer anyway.

```
% mvn dependency:tree | grep protob
[INFO] |  \- com.google.protobuf:protobuf-java:jar:3.9.1:compile
```

**Comment by HarrietMa** [comment]
Okay. Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElectronicChartCentre/java-vector-tile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ElectronicChartCentre/java-vector-tile] Some errors in spark (#40)





 
Okay. I do not have any other suggestion. However, we should probably upgrade our protobuf version to something newer anyway.
 % mvn dependency:tree | grep protob [INFO] |  \- com.google.protobuf:protobuf-java:jar:3.9.1:compile
