### ISSUE TITLE
Allow VectorTileEncoder subclasses to do their own validation, in addition to their own clipping

### ISSUE THREAD

**Issue by aaime** [ElectronicChartCentre/java-vector-tile#48]
VectorTileEncoder allows for custom clipping, but then performs expensive validation operations, in terms of decoding the generated commands as well as calling Geometry.isValid, which is a pretty expensive operation in general.

Could you allow subclasses to opt-out of both these operations (the decoding and the validation)?

**Comment by halset** [comment]
@aaime , can you take a look at #49?

**Comment by halset** [comment]
This is part of 1.3.22.
