### ISSUE TITLE
Decoding vector tile data from osm2vectortiles project

### ISSUE THREAD

**Issue by dfdietrick** [ElectronicChartCentre/java-vector-tile#8]
I'm trying to write Java code to display the vector tile data, using OpenMap combined with the java-vector-tile decoder.  When I pull the tile_data byte array out of the database, the java-vector-tile decoder doesn't read it correctly.  I've compared the bytes with other tile data bytes I've received from servers, and it seems off - it looks really different, like it's encoded, compressed or something.  I've tried running the bytes through Base64/zip decoding, but that doesn't help.  Is there a trick to getting the java-vector-tile decoder to work on that data?

**Comment by dfdietrick** [comment]
Got the answer on the osm2vectortiles side, the tile_data is gzipped.

**Comment by halset** [comment]
Glad to hear you figured this out, Don!

**Comment by dfdietrick** [comment]
Thanks!  I'm displaying plain polygon features now, working on rendering styles and the other geometry types. 

-- Don
